openapi: 3.0.3
info:
  title: commander
  description: ''
  license:
    name: ''
  version: 0.1.0
paths: {}
components:
  schemas:
    Person:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
