openapi: 3.0.3
info:
  title: commander
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /api/v1/media-searches:
    get:
      tags:
      - crate::search
      operationId: search_media
      responses:
        '200':
          description: Search media files
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaFileGroup'
components:
  schemas:
    MediaFileGroup:
      type: object
      required:
      - path
      - name
      - videos
      properties:
        name:
          type: string
        path:
          type: string
        videos:
          type: array
          items:
            type: string
tags:
- name: search
  description: Search media API
