# Sample settings, please use as reference only, fill in real values. 
server_port = 7878

[mongodb]
connection_url = "mongo://something"
database = "videosmover"
download_collection = "download_cache"
online_collection = "online_cache"

[tmdb]
api_key = "myApiKey"
base_url = "https://api.themoviedb.org/3/"
search_movies_url = "{base_url}search/movie?api_key={api_key}&query={query}&year={year}"
movie_credits_url = "{base_url}movie/{id}/credits?api_key={api_key}"
search_tv_url = "{base_url}search/tv?api_key={api_key}&query={query}&year={year}"
tv_credits_url = "{base_url}tv/{id}/credits?api_key={api_key}"

[online]
result_limit = 10
poster_base = "http://image.tmdb.org/t/p/w92"

[server]
command_name = "winlegion"
command_listen_cron = "0/10 0/1 * 1/1 * ? *"

[filesystem]
downloads_path = "randomly generated in tmp dir"
movies_path = "randomly generated in tmp dir"
tv_path = "randomly generated in tmp dir"

[search]
max_depth = 2
exclude_paths = [ "exclude", "another/exclude" ]
video_min_size_bytes = 5
video_mime_types = [ "text/plain" ]

[rename]
trim_regex = [ ".[sS](\\d{1,2})([-]?[eE](\\d{1,2}))?", "[\\.\\s][sS][0-9]{1,2}[\\.\\s]?", "1080p", "720p", "2160p", "BluRay", "HDTV", "x264", "REPACK", "WEB-DL", "BRRip", "H264", "AAC", "XviD", "AC3", "HDRip", "DVDRip", "WEBRip", "DVDScr", "HQ", "KORSUB", "BDRip", ".?RARBG", "(\\d|\\.){1,5}(GB|MB)", "\\.EXTENDED\\.", "MP3", "(DD)?5\\.1", "DTS" ]
similarity_percent = 80
max_depth = 1

[mv]
restricted_remove_paths = [ "downloads", "movies", "tv", "some/folder/to/exclude/from/delete/2" ]
subs_ext = [ "srt", "sub", "ssa", "ass", "usf", "idx", "ssf", "stl", "smi", "rt", "psb", "pjs", "ttxt", "jss", "gsub", "aqt", "nfo" ]
subs_max_depth = 5
